#!/bin/bash

#
# sets up directory structure and generates, configures and submits
# scripts to run a BWA paired-end mappings on a set of fastq files
#

#CONFIGURATION
##############

#now
NOW="date +%Y-%m-%d%t%T%t"

#today
TODAY=`date +%Y-%m-%d`

#returns absolute path to qfastqc directory, not changing your current directory
BASEDIR="$( cd "$( dirname "$0" )" && pwd )"
GROUP_VOL_CGI=/groupvol/cgi
GROUP_VOL_TGU=/project/tgu
DEPLOYMENT_SERVER=eliot.med.ic.ac.uk
DEPLOYMENT_BASE_DIR=/www/html/report

QUEUE=pqcgi
WALLTIME_HOURS_PER_RUN=30

USAGE="$BASEDIR/qbwape.usage"

#BWA
####

READS_PER_RUN=10000000
THREADS_PER_RUN=2
PATH_REFERENCE_FASTA=$GROUP_VOL_CGI/resources/reference/eukaryote/human/hs37d5/bwa_indexed/hs37d5.fa
MULT_READS=F
PATTERN_READ_1='_R1_'
PATTERN_READ_2='_R2_'

SPLITFASTQ_WALLTIME_HOURS=72
SPLITFASTQ_THREADS=4


#COMMAND LINE ARGS
##################

#TODO: have to do conversion for Illumina 1.3 formated files with Michael's perl script
 
while getopts "i:n:r:t:p:f:hm:c" option; do
    case "$option" in
	
	i) INPUT_PATH="$OPTARG";;
	n) PROJECT="$OPTARG";;
	r) PATH_REFERENCE_FASTA="$OPTARG";;
	t) PATTERN_READ_1="$OPTARG";;
	p) PATTERN_READ_2="$OPTARG";;
	f) echo "-f option is not supported by the current version of bwa";;
	m) MULT_READS=T;;
	c) CRAM="T";;
	h) cat "$USAGE"; exit 0;;
	[?]) cat "$USAGE"; exit 1;;

esac
done

#check if required arguments are missing
if [ -z $INPUT_PATH ] || [ -z $PROJECT ]

    then
    cat "$USAGE"
    exit 1

fi


#FUNCTIONS
##########

#creates job scripts
function submitJobs {

	PATH_READS_DIRECTORY=$1
	PATH_REFERENCE_FASTA=$2
	PATH_ANALYSIS_DIR=$3
	PATH_RUN_DIR=$4
	PATH_OUT_DIR=$5
	PATTERN_READ_1=$6
	PATTERN_READ_2=$7
	THREADS_PER_RUN=$8
	READS_PER_RUN=$9
	WALLTIME_HOURS_PER_RUN=${10}
	DEPLOYMENT_SERVER=${11}
	SUMMARY_DEPLOYMENT=${12}
	SUMMARY_RESULTS=${13}
	MULT_READS=${14}

	PATH_SCRIPTS_DIR=$PATH_RUN_DIR/run      
	PATH_MAPPING_DIR=$PATH_ANALYSIS_DIR/mapping
	PATH_TMP_DIR=$PATH_ANALYSIS_DIR/tmp
	PATH_RESULTS_DIR=$PATH_OUT_DIR

	mkdir -m 770 -p $PATH_SCRIPTS_DIR
	mkdir -m 770 -p $PATH_MAPPING_DIR
	mkdir -m 770 -p $PATH_TMP_DIR
	mkdir -m 770 -p $PATH_RESULTS_DIR

	# to make sure the directories have correct 
	# permissions (since -p creates u+wx for parent directories)
	chmod -R 770 $PATH_ANALYSIS_DIR
	chmod -R 770 $PATH_RUN_DIR
	chmod -R 770 $PATH_OUT_DIR

	SETUP_LOG=$PATH_RUN_DIR/run/setup.log

	echo -n "" > $SETUP_LOG

	echo "`$NOW`setting up BWA mapping run(s)... "
	echo "`$NOW`(see $SETUP_LOG for details)"

	echo "`$NOW`setting up BWA mapping run(s)" >> $SETUP_LOG
	echo "`$NOW`read directory: $PATH_READS_DIRECTORY" >> $SETUP_LOG
	echo "`$NOW`pattern mate pair 1 reads: $PATTERN_READ_1" >> $SETUP_LOG
	echo "`$NOW`pattern mate pair 2 reads: $PATTERN_READ_2" >> $SETUP_LOG
	echo "`$NOW`reference file: $PATH_REFERENCE_FASTA" >> $SETUP_LOG
	echo "`$NOW`reads per BWA mapping run: $READS_PER_RUN" >> $SETUP_LOG
	echo "`$NOW`script directory: $PATH_SCRIPTS_DIR" >> $SETUP_LOG
	echo "`$NOW`mapping directory: $PATH_MAPPING_DIR" >> $SETUP_LOG
	echo "`$NOW`result directory: $PATH_RESULTS_DIR" >> $SETUP_LOG
 

	#get reference FASTA file names
	REFERENCE_FASTA_NAME=`basename $PATH_REFERENCE_FASTA .gz`

	#get reference FASTA directory path
	PATH_REFERENCE_FASTA_DIR=`dirname $PATH_REFERENCE_FASTA`

	PATH_REFERENCE_FASTA_NO_EXT=$PATH_REFERENCE_FASTA_DIR/$REFERENCE_FASTA_NAME

	echo "`$NOW`creating and submitting job scripts:" >> $SETUP_LOG

	#for each fastq file (fastq files have to be gzipped and 
	#have to have a fq.gz or fastq.gz extension
	for FASTQ_READ1 in `ls --color=never $PATH_READS_DIRECTORY/*.f*q* | grep $PATTERN_READ_1`
	do 
		FASTQ_READ1=`basename $FASTQ_READ1`

		#find read2 mate file
		FASTQ_READ2=""
		for FASTQ in `ls --color=never $PATH_READS_DIRECTORY/*.f*q* | grep $PATTERN_READ_2`
		do	

		    FASTQ=`basename $FASTQ`

    		    FASTQ_REPLACE=`echo $FASTQ | perl -pe "s/$PATTERN_READ_2/$PATTERN_READ_1/"`

    		    if [ "$FASTQ_REPLACE" = "$FASTQ_READ1" ]; 
    		    then
			FASTQ_READ2=$FASTQ       
    		    fi
    		done;

		FASTQ_READ1_NO_EXT=`basename $FASTQ_READ1 .gz`
    		FASTQ_READ2_NO_EXT=`basename $FASTQ_READ2 .gz`

		PATH_READS_FASTQ_READ1=$PATH_READS_DIRECTORY/$FASTQ_READ1_NO_EXT
		PATH_READS_FASTQ_READ2=$PATH_READS_DIRECTORY/$FASTQ_READ2_NO_EXT
             
	         #check if mate file found
		if [ -z $FASTQ_READ2 ]
		then
			cat "No mate file found for $FASTQ_READ1. Skipped." >> $SETUP_LOG
			continue    		
		fi

		#create directory structure for merged bam files 
		#each file will contain the same reads as in the original fastq file
		echo "`$NOW`creating BWA results directory $PATH_RESULTS_DIR" >> $SETUP_LOG
		mkdir -m 770 -p $PATH_RESULTS_DIR

		# change permissions for the parent directories:
		chmod -R 770 $PATH_RESULTS_DIR


		#unzip file and count entries
		echo "`$NOW`read pair: $FASTQ_READ1_NO_EXT $FASTQ_READ2_NO_EXT" >> $SETUP_LOG 

		#split fastq files
		echo "`$NOW`submitting jobs to split fastq files into $READS_PER_RUN chunks... " >> $SETUP_LOG
	   	
		LINES_PER_FILE=$(($READS_PER_RUN * 4))

		#variables to store job dependencies
		SPLIT_DEPENDENCIES=afterok

		#create temporary directory for split files
		SPLITFASTQ_OUTPUT_DIR=$PATH_TMP_DIR/${FASTQ_READ1_NO_EXT}_split
		mkdir -p $SPLITFASTQ_OUTPUT_DIR

		#submit splitting jobs
		for FASTQ in $PATH_READS_DIRECTORY/$FASTQ_READ1 $PATH_READS_DIRECTORY/$FASTQ_READ2
		do
		
			FASTQ_NAME=`basename $FASTQ .gz`
			
			#calculate required temp space
			FILE_SIZE_KB=`du $FASTQ | cut -f1`

			if [[ "$FILE_SIZE_KB" -ne "0" ]]
			then
				FILE_SIZE_MB=$(( $FILE_SIZE_KB / 1024 ))
				TMP_SPACE_MB=$(( $FILE_SIZE_MB * 2 ))
			fi

			SCRIPT_PATH=$PATH_SCRIPTS_DIR/splitFastq.$FASTQ_NAME.sh
			cp $BASEDIR/splitFastq.sh $SCRIPT_PATH
			chmod 770 $SCRIPT_PATH

			sed -i -e "s/#walltimeHours/$SPLITFASTQ_WALLTIME_HOURS/" $SCRIPT_PATH  
			sed -i -e "s/#threads/$SPLITFASTQ_THREADS/" $SCRIPT_PATH
			sed -i -e "s/#tmpSpace/$TMP_SPACE_MB/" $SCRIPT_PATH
			sed -i -e "s/#inputFastq/${FASTQ//\//\\/}/" $SCRIPT_PATH
			sed -i -e "s/#outputDir/${SPLITFASTQ_OUTPUT_DIR//\//\\/}/" $SCRIPT_PATH
			sed -i -e "s/#readsPerChunk/$READS_PER_RUN/" $SCRIPT_PATH

			LOG_PATH=`echo $SCRIPT_PATH | perl -pe 's/\.sh/\.log/g'`

			echo "`$NOW`submitting fastq splitting job:" >> $SETUP_LOG
			echo "`$NOW`splitFastq.$FASTQ_NAME.sh" >> $SETUP_LOG
			echo -n "`$NOW`" >> $SETUP_LOG

			#echo qsub -q $QUEUE -o $LOG_PATH $SCRIPT_PATH
			JOB_ID=`qsub -o $LOG_PATH $SCRIPT_PATH` 
			echo $JOB_ID  >> $SETUP_LOG

			SPLIT_DEPENDENCIES="$SPLIT_DEPENDENCIES:$JOB_ID"

		done;

		OUTPUT_PREFIX=$FASTQ_READ1_NO_EXT.vs.$REFERENCE_FASTA_NAME

		SCRIPT_PATH=$PATH_SCRIPTS_DIR/submitMappingScript.$OUTPUT_PREFIX.sh
		cp $BASEDIR/submitMappingScript.sh $SCRIPT_PATH
		chmod 770 $SCRIPT_PATH

		sed -i -e "s/#baseDir/${BASEDIR//\//\\/}/" $SCRIPT_PATH
		sed -i -e "s/#setupLog/${SETUP_LOG//\//\\/}/" $SCRIPT_PATH
		sed -i -e "s/#pathTmpDir/${PATH_TMP_DIR//\//\\/}/" $SCRIPT_PATH
		sed -i -e "s/#fastqRead1NoExt/$FASTQ_READ1_NO_EXT/" $SCRIPT_PATH
		sed -i -e "s/#patternRead1/$PATTERN_READ_1/" $SCRIPT_PATH
		sed -i -e "s/#patternRead2/$PATTERN_READ_2/" $SCRIPT_PATH
		sed -i -e "s/#threadsPerRun/$THREADS_PER_RUN/" $SCRIPT_PATH
		sed -i -e "s/#queue/$QUEUE/" $SCRIPT_PATH
		sed -i -e "s/#walltimeHoursPerRun/$WALLTIME_HOURS_PER_RUN/" $SCRIPT_PATH
		sed -i -e "s/#pathScriptsDir/${PATH_SCRIPTS_DIR//\//\\/}/" $SCRIPT_PATH
		sed -i -e "s/#pathResultsDir/${PATH_RESULTS_DIR//\//\\/}/" $SCRIPT_PATH
		sed -i -e "s/#pathMappingDir/${PATH_MAPPING_DIR//\//\\/}/" $SCRIPT_PATH		
		sed -i -e "s/#pathReferenceFastaNoExt/${PATH_REFERENCE_FASTA_NO_EXT//\//\\/}/" $SCRIPT_PATH
		sed -i -e "s/#pathRunDir/${PATH_RUN_DIR//\//\\/}/" $SCRIPT_PATH
		sed -i -e "s/#today/$TODAY/" $SCRIPT_PATH
		sed -i -e "s/#deploymentServer/$DEPLOYMENT_SERVER/" $SCRIPT_PATH
		sed -i -e "s/#summaryDeployment/${SUMMARY_DEPLOYMENT//\//\\/}/" $SCRIPT_PATH
		sed -i -e "s/#summaryResults/${SUMMARY_RESULTS//\//\\/}/" $SCRIPT_PATH

		if [[ "$CRAM" == "T" ]]; then
			SAMPLE_NAME=`basename $PATH_RESULTS_DIR`		
			PATH_OUTPUT_CRAM_DIR=/project/tgu/rawdata/$PROJECT/cram/$SAMPLE_NAME
			if [ ! -d $PATH_OUTPUT_CRAM_DIR ]; then mkdir -m 770 $PATH_OUTPUT_CRAM_DIR; fi
			sed -i -e "s/#cram2BamConversion/$CRAM/" $SCRIPT_PATH
			sed -i -e "s/#pathOutputCramDir/${PATH_OUTPUT_CRAM_DIR//\//\\/}/" $SCRIPT_PATH
		fi

		LOG_PATH=`echo $SCRIPT_PATH | perl -pe 's/\.sh/\.log/g'`

		echo "`$NOW`submitting submitMappingScript job:" >> $SETUP_LOG
		echo "`$NOW`submitMappingScript.$OUTPUT_PREFIX.sh" >> $SETUP_LOG
		echo -n "`$NOW`" >> $SETUP_LOG

		JOB_ID=`qsub -W depend=$SPLIT_DEPENDENCIES -o $LOG_PATH $SCRIPT_PATH` 
		echo $JOB_ID >> $SETUP_LOG

	done;

	echo "`$NOW`done"

}

#if the input path is a CGI project directory...
if [ -d $INPUT_PATH ]; then

    echo "`$NOW`input path is CGI project directory"

    #create and set permissions for analysis project parent directory
    mkdir -p $GROUP_VOL_CGI/analysis/$PROJECT
    chmod 770 $GROUP_VOL_CGI/analysis/$PROJECT

    mkdir -p $GROUP_VOL_CGI/analysis/$PROJECT/bwa
    chmod 770 $GROUP_VOL_CGI/analysis/$PROJECT/bwa

    mkdir -p $GROUP_VOL_CGI/analysis/$PROJECT/bwa/$TODAY
    chmod 770 $GROUP_VOL_CGI/analysis/$PROJECT/bwa/$TODAY

    #create and set permissions for runs project parent directory
    mkdir -p $GROUP_VOL_TGU/runs/$PROJECT
    chmod 770 $GROUP_VOL_TGU/runs/$PROJECT

    mkdir -p $GROUP_VOL_TGU/runs/$PROJECT/bwa
    chmod 770 $GROUP_VOL_TGU/runs/$PROJECT/bwa

    mkdir -p $GROUP_VOL_TGU/runs/$PROJECT/bwa/$TODAY
    chmod 770 $GROUP_VOL_TGU/runs/$PROJECT/bwa/$TODAY

    #create and set permissions for results project parent directory
    mkdir -p $GROUP_VOL_TGU/results/$PROJECT
    chmod 770 $GROUP_VOL_TGU/results/$PROJECT

    mkdir -p $GROUP_VOL_TGU/results/$PROJECT/bwa
    chmod 770 $GROUP_VOL_TGU/results/$PROJECT/bwa

    mkdir -p $GROUP_VOL_TGU/results/$PROJECT/bwa/$TODAY
    chmod 770 $GROUP_VOL_TGU/results/$PROJECT/bwa/$TODAY

    SUMMARY_RESULTS=$GROUP_VOL_TGU/results/$PROJECT/bwa/$TODAY
    SUMMARY_DEPLOYMENT=$DEPLOYMENT_BASE_DIR/project/$PROJECT/bwa/$TODAY
    ssh $DEPLOYMENT_SERVER "mkdir -p -m 775 $SUMMARY_DEPLOYMENT" > /dev/null 2>&1
    scp -r ${BASEDIR}/../../resources/images/error.png $DEPLOYMENT_SERVER:$SUMMARY_DEPLOYMENT/ > /dev/null 2>&1
    scp -r ${BASEDIR}/../../resources/images/tick.png $DEPLOYMENT_SERVER:$SUMMARY_DEPLOYMENT/ > /dev/null 2>&1
    scp -r ${BASEDIR}/../../resources/images/warning.png $DEPLOYMENT_SERVER:$SUMMARY_DEPLOYMENT/ > /dev/null 2>&1
    ssh $DEPLOYMENT_SERVER "chmod -R 664 $SUMMARY_DEPLOYMENT/*png" > /dev/null 2>&1

    #for each sample directory...
    for SAMPLE in `ls --color=never $INPUT_PATH`
    do

	FASTQ_DIR=$INPUT_PATH/$SAMPLE

	if [ -d $FASTQ_DIR ]; then

		#count fastq files in directory		
		FASTQ_COUNT=`ls --color=never $FASTQ_DIR/*.f*q* | wc -l`

		if [ $FASTQ_COUNT -gt 0 ]; then

			echo "`$NOW`processing directory $SAMPLE..."

			#create and set permissions for analysis sample parent directory
			mkdir -p $GROUP_VOL_CGI/analysis/$PROJECT/bwa/$TODAY/$SAMPLE
			chmod 770 $GROUP_VOL_CGI/analysis/$PROJECT/bwa/$TODAY/$SAMPLE

 			#create and set permissions for results sample parent directory
   			mkdir -p $GROUP_VOL_TGU/results/$PROJECT/bwa/$TODAY/$SAMPLE
    			chmod 770 $GROUP_VOL_TGU/results/$PROJECT/bwa/$TODAY/$SAMPLE

 			#create and set permissions for runs sample parent directory
   			mkdir -p $GROUP_VOL_TGU/runs/$PROJECT/bwa/$TODAY/$SAMPLE
    			chmod 770 $GROUP_VOL_TGU/runs/$PROJECT/bwa/$TODAY/$SAMPLE

        		#...create output directory
			PATH_ANALYSIS_DIR=$GROUP_VOL_CGI/analysis/$PROJECT/bwa/$TODAY/$SAMPLE
			PATH_RUN_DIR=$GROUP_VOL_TGU/runs/$PROJECT/bwa/$TODAY/$SAMPLE 
			PATH_OUT_DIR=$GROUP_VOL_TGU/results/$PROJECT/bwa/$TODAY/$SAMPLE      
	
			#create, configure and submit job scripts
			submitJobs $FASTQ_DIR \
                                   $PATH_REFERENCE_FASTA \
				   $PATH_ANALYSIS_DIR \
                                   $PATH_RUN_DIR \
                                   $PATH_OUT_DIR \
                                   $PATTERN_READ_1 \
                                   $PATTERN_READ_2 \
                                   $THREADS_PER_RUN \
                                   $READS_PER_RUN \
				   $WALLTIME_HOURS_PER_RUN \
                                   $DEPLOYMENT_SERVER \
                                   $SUMMARY_DEPLOYMENT \
                                   $SUMMARY_RESULTS \
                                   $MULT_READS
		
		else
			echo "`$NOW`directory $SAMPLE does not contain any fastq files (.fq or .fastq file extension)"	
		fi

	fi

    done;

    echo "`$NOW`progress and summary of bwa runs can be seen at $DEPLOYMENT_SERVER/report/project/$PROJECT/bwa/$TODAY/"

else
    echo "`$NOW`Error: Input path is not a directory."
    exit 1
fi

