#!/bin/bash

# configures scripts for EDASeq normalization run 

#CONFIGURATION
###################

#today
TODAY=`date +%Y-%m-%d`

#returns absolute path to DESeq directory, not changing your current directory
BASEDIR="$( cd "$( dirname "$0" )" && pwd )"

GROUP_VOL_TGU=/project/tgu
WALLTIME_HOURS_PER_RUN=72
USAGE=$BASEDIR/qfiltering.usage
ANALYSIS_NAME=DESeq
HTSEQ=F
DISPERSION=maximum
SUBFOLDER=""
FILTERING_STATS=max
FILTERING_CUTOFF=0.4
GFF_PATH="/project/tgu/resources/reference/hsapiens/GRCh37/annotation/GRCh37.transcripts.gff"
GO_PATH="/project/tgu/resources/reference/hsapiens/GRCh37/annotation/GRCh37.go.txt"
GENE_GCCONT="/project/tgu/resources/reference/hsapiens/GRCh37/annotation/GRCh37.genegc.txt"
GENE_LENGTH="/project/tgu/resources/reference/hsapiens/GRCh37/annotation/GRCh37.genelen.txt"

#COMMAND LINE ARGS
####################
while getopts "i:f:tn:o:d:s:u:a:g:c:l:h" option; do
    case "$option" in
	
	i) COUNTS_TABLE="$OPTARG";;
	f) DESIGN_FILE="$OPTARG";;
	t) HTSEQ=T;;
        n) PROJECT="$OPTARG";;
	o) SUBFOLDER="$OPTARG";;
	d) DISPERSION="$OPTARG";;
	s) FILTERING_STATS="$OPTARG";;
	u) FILTERING_CUTOFF="$OPTARG";;
	a) GFF_PATH="$OPTARG";;
	g) GO_PATH="$OPTARG";;
	c) GENE_GCCONT="$OPTARG";;
	l) GENE_LENGTH="$OPTARG";;
	h) cat $USAGE;;
	[?]) cat $USAGE;;

esac
done

if [ -z $COUNTS_TABLE ] || \
   [ -z $DESIGN_FILE ] || \
   [ -z $PROJECT ]
    then
    cat $USAGE
    exit 1
fi

if [ $DISPERSION != 'maximum' ] && [ $DISPERSION != 'gene' ] && [ $DISPERSION != 'fit' ]
then
    echo "Wrong choice of dispertion mode."
    exit 1
fi

if [ $FILTERING_STATS != 'max' ] && [ $FILTERING_STATS != 'min' ] && [ $FILTERING_STATS != 'mean' ] && [ $FILTERING_STATS != 'sd' ]
then
    echo "Wrong choice of dispertion modefiltering statistics."
    exit 1
fi

#create and set permissions for analysis project parent directory
SCRIPTS_DIR="$GROUP_VOL_TGU/runs/$PROJECT/$ANALYSIS_NAME/$TODAY/$SUBFOLDER"."$FILTERING_STATS"."$FILTERING_CUTOFF"."filt.norm"
mkdir -p $SCRIPTS_DIR
chmod 770 $SCRIPTS_DIR

#create and set permissions for results project parent directory
RESULTS_DIR="$GROUP_VOL_TGU/results/$PROJECT/$ANALYSIS_NAME/$TODAY/$SUBFOLDER"."$FILTERING_STATS"."$FILTERING_CUTOFF"."filt.norm"
mkdir -p $RESULTS_DIR
chmod 770 $RESULTS_DIR

#create and edit scripts for running DESeq
SHELL_SCRIPT_PATH=$SCRIPTS_DIR/normalization.sh
cp $BASEDIR/normalization.sh $SHELL_SCRIPT_PATH
chmod 770 $SHELL_SCRIPT_PATH

R_SCRIPT_PATH=$SCRIPTS_DIR/normalization.R
cp $BASEDIR/normalization.R $R_SCRIPT_PATH
chmod 770 $R_SCRIPT_PATH

sed -i -e "s/#walltimeHours/$WALLTIME_HOURS_PER_RUN/" $SHELL_SCRIPT_PATH
sed -i -e "s/#rScript/${R_SCRIPT_PATH//\//\\/}/" $SHELL_SCRIPT_PATH
sed -i -e "s/#resultsDir/${RESULTS_DIR//\//\\/}/" $SHELL_SCRIPT_PATH
sed -i -e "s/#gffPath/${GFF_PATH//\//\\/}/" $SHELL_SCRIPT_PATH
sed -i -e "s/#goPath/${GO_PATH//\//\\/}/" $SHELL_SCRIPT_PATH

sed -i -e "s/#resultsDir/${RESULTS_DIR//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#countsTable/${COUNTS_TABLE//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#designFile/${DESIGN_FILE//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#htSeq/$HTSEQ/" $R_SCRIPT_PATH
sed -i -e "s/#dispertionMode/$DISPERSION/" $R_SCRIPT_PATH
sed -i -e "s/#filteringStats/$FILTERING_STATS/" $R_SCRIPT_PATH
sed -i -e "s/#filteringCutoff/$FILTERING_CUTOFF/" $R_SCRIPT_PATH
sed -i -e "s/#CGcontent/${GENE_GCCONT//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#geneLength/${GENE_LENGTH//\//\\/}/" $R_SCRIPT_PATH

#submit job
LOG_PATH=`echo $SHELL_SCRIPT_PATH | perl -pe 's/\.sh/\.log/g'`
echo "`$NOW`$SHELL_SCRIPT_PATH"
JOB_ID=`qsub -o $LOG_PATH -q pqcgi $SHELL_SCRIPT_PATH`
echo "$JOB_ID"

