#!/bin/bash

# sets up directory structure and configures scripts for DESeq run

#CONFIGURATION
###################

#today
TODAY=`date +%Y-%m-%d`

#returns absolute path to DESeq directory, not changing your current directory
BASEDIR="$( cd "$( dirname "$0" )" && pwd )"

GROUP_VOL_TGU=/project/tgu
WALLTIME_HOURS_PER_RUN=72
USAGE=$BASEDIR/qDESeq.usage
ANALYSIS_NAME=DESeq
HTSEQ=F
DISPERSION=maximum
SUBFOLDER=""


#COMMAND LINE ARGS
####################
while getopts "i:f:tn:o:d:s:u:h" option; do
    case "$option" in
	
	i) COUNTS_TABLE="$OPTARG";;
	f) DESIGN_FILE="$OPTARG";;
	t) HTSEQ=T;;
        n) PROJECT="$OPTARG";;
	o) SUBFOLDER="$OPTARG";;
	d) DISPERSION="$OPTARG";;
	s) FILTERING_STATS="$OPTARG";;
	u) FILTERING_CUTOFF="$OPTARG";;
	h) cat $USAGE;;
	[?]) cat $USAGE;;

esac
done

if [ -z $COUNTS_TABLE ] || \
   [ -z $DESIGN_FILE ] || \
   [ -z $PROJECT ]
    then
    cat $USAGE
    exit 1
fi

if [ $DISPERSION != 'maximum' ] && [ $DISPERSION != 'gene' ] && [ $DISPERSION != 'fit' ]
then
    echo "Wrong choice of dispertion mode."
    exit 1
fi

if [ $FILTERING_STATS != 'max' ] && [ $FILTERING_STATS != 'min' ] && [ $FILTERING_STATS != 'mean' ] && [ $FILTERING_STATS != '' ]
then
    echo "Wrong choice of dispertion modefiltering statistics."
    exit 1
fi

#create and set permissions for analysis project parent directory

mkdir -p $GROUP_VOL_TGU/runs/$PROJECT
chmod 770 $GROUP_VOL_TGU/runs/$PROJECT

mkdir -p $GROUP_VOL_TGU/runs/$PROJECT/$ANALYSIS_NAME
chmod 770 $GROUP_VOL_TGU/runs/$PROJECT/$ANALYSIS_NAME

mkdir -p $GROUP_VOL_TGU/runs/$PROJECT/$ANALYSIS_NAME/$TODAY
chmod 770 $GROUP_VOL_TGU/runs/$PROJECT/$ANALYSIS_NAME/$TODAY

#create and set permissions for results project parent directory
mkdir -p $GROUP_VOL_TGU/results/$PROJECT
chmod 770 $GROUP_VOL_TGU/results/$PROJECT

mkdir -p $GROUP_VOL_TGU/results/$PROJECT/$ANALYSIS_NAME
chmod 770 $GROUP_VOL_TGU/results/$PROJECT/$ANALYSIS_NAME

mkdir -p $GROUP_VOL_TGU/results/$PROJECT/$ANALYSIS_NAME/$TODAY
chmod 770 $GROUP_VOL_TGU/results/$PROJECT/$ANALYSIS_NAME/$TODAY

if [ $FILTERING_STATS == '' ]
then 

	RESULTS_DIR=$GROUP_VOL_TGU/results/$PROJECT/$ANALYSIS_NAME/$TODAY/$SUBFOLDER
	mkdir -p $RESULTS_DIR
	chmod 770 $RESULTS_DIR

	SCRIPTS_DIR=$GROUP_VOL_TGU/runs/$PROJECT/$ANALYSIS_NAME/$TODAY/$SUBFOLDER
	mkdir -p $SCRIPTS_DIR
	chmod 770 $SCRIPTS_DIR

	#create and edit scripts for running DESeq
	SHELL_SCRIPT_PATH=$SCRIPTS_DIR/DESeq.sh
	cp $BASEDIR/DESeq.sh $SHELL_SCRIPT_PATH
	chmod 770 $SHELL_SCRIPT_PATH
	
	R_SCRIPT_PATH=$SCRIPTS_DIR/DESeq.R
	cp $BASEDIR/DESeq.R $R_SCRIPT_PATH
	chmod 770 $R_SCRIPT_PATH

else 
  
	SCRIPTS_DIR="$GROUP_VOL_TGU/runs/$PROJECT/$ANALYSIS_NAME/$TODAY/$SUBFOLDER"."$FILTERING_STATS"."$FILTERING_CUTOFF"."filt"
	mkdir -p $SCRIPTS_DIR
	chmod 770 $SCRIPTS_DIR

	RESULTS_DIR="$GROUP_VOL_TGU/results/$PROJECT/$ANALYSIS_NAME/$TODAY/$SUBFOLDER"."$FILTERING_STATS"."$FILTERING_CUTOFF"."filt"
	mkdir -p $RESULTS_DIR
	chmod 770 $RESULTS_DIR

	#create and edit scripts for running DESeq
	SHELL_SCRIPT_PATH=$SCRIPTS_DIR/filtering.sh
	cp $BASEDIR/filtering.sh $SHELL_SCRIPT_PATH
	chmod 770 $SHELL_SCRIPT_PATH

	R_SCRIPT_PATH=$SCRIPTS_DIR/filtering.R
	cp $BASEDIR/filtering.R $R_SCRIPT_PATH
	chmod 770 $R_SCRIPT_PATH

fi

sed -i -e "s/#walltimeHours/$WALLTIME_HOURS_PER_RUN/" $SHELL_SCRIPT_PATH
sed -i -e "s/#rScript/${R_SCRIPT_PATH//\//\\/}/" $SHELL_SCRIPT_PATH
sed -i -e "s/#resultsDir/${RESULTS_DIR//\//\\/}/" $SHELL_SCRIPT_PATH

sed -i -e "s/#resultsDir/${RESULTS_DIR//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#countsTable/${COUNTS_TABLE//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#designFile/${DESIGN_FILE//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#htSeq/$HTSEQ/" $R_SCRIPT_PATH
sed -i -e "s/#dispertionMode/$DISPERSION/" $R_SCRIPT_PATH
sed -i -e "s/#filteringStats/$FILTERING_STATS/" $R_SCRIPT_PATH
sed -i -e "s/#filteringCutoff/$FILTERING_CUTOFF/" $R_SCRIPT_PATH


#submit job
LOG_PATH=`echo $SHELL_SCRIPT_PATH | perl -pe 's/\.sh/\.log/g'`
echo "`$NOW`$SHELL_SCRIPT_PATH"
JOB_ID=`qsub -o $LOG_PATH -q pqcgi $SHELL_SCRIPT_PATH`
echo "$JOB_ID"







