#!/bin/bash

# creates and submits scripts to run MEDIPS 
# quality control on the input bam files

USAGE="qQualityMetrics -i <input_dir> -n <project_name> -r <sample_info> -l <extension_length> -p <TRUE_for_paired> -w <window_size>"

#now
NOW="date +%Y-%m-%d%t%T%t"

#today
TODAY=`date +%Y-%m-%d`

R_VERSION=3.0.1

QUEUE=pqcgi
GROUPVOL_TGU=/project/tgu
BASEDIR="$( cd "$( dirname "$0" )" && pwd )"
DEPLOYMENT_SERVER=eliot.med.ic.ac.uk
DEPLOYMENT_BASE_DIR=/www/html/report
EXTEND=100
PAIRED=TRUE
WINDOW=200

#parse command line args
while getopts "i:n:r:l:p:w:h" option; do
    case "$option" in
	
	i) INPUT_DIR="$OPTARG";;
	n) PROJECT="$OPTARG";;
	r) SAMPLE_INFO="$OPTARG";;
	l) EXTEND="$OPTARG";;
	p) PAIRED="$OPTARG";;
	w) WINDOW="$OPTARG";;
	h) cat $USAGE; exit 0;;
	[?]) cat $USAGE; exit 1;;

esac
done

# check for presence of required input parameters
if [ -z $INPUT_DIR ] || [ -z $PROJECT ] || [ -z $SAMPLE_INFO ]; then
        echo "Error: Required input argument missing."
        cat $USAGE
        exit 1
fi


mkdir -p $GROUPVOL_TGU/results/$PROJECT/medips-QC
chmod 770 $GROUPVOL_TGU/results/$PROJECT/medips-QC

mkdir -p $GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY
chmod 770 $GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY

mkdir -p $GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY/multisample
chmod 770 $GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY/multisample

mkdir -p $GROUPVOL_TGU/runs/$PROJECT/medips-QC
chmod 770 $GROUPVOL_TGU/runs/$PROJECT/medips-QC

mkdir -p $GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY
chmod 770 $GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY

mkdir -p $GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/multisample
chmod 770 $GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/multisample

SUMMARY_DEPLOYMENT=$DEPLOYMENT_BASE_DIR/project/$PROJECT/medips-QC/$TODAY
ssh $DEPLOYMENT_SERVER "mkdir -p $SUMMARY_DEPLOYMENT" > /dev/null 2>&1
ssh $DEPLOYMENT_SERVER "chmod  775 $DEPLOYMENT_BASE_DIR/project/$PROJECT/medips-QC" > /dev/null 2>&1
ssh $DEPLOYMENT_SERVER "chmod  775 $DEPLOYMENT_BASE_DIR/project/$PROJECT/medips-QC/$TODAY" > /dev/null 2>&1

MEDIPS_DEPENDECIES="afterany"
SAMPLES=""

for SAMPLE in `sed 1d $SAMPLE_INFO | cut -f1 | grep -vP "^$"`;do

	echo "`$NOW`###########################################################################################"
	echo "`$NOW`sample $SAMPLE"

	SAMPLES="$SAMPLES $SAMPLE"

	mkdir -p $GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY/$SAMPLE
	chmod 770 $GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY/$SAMPLE

	mkdir -p $GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/$SAMPLE
	chmod 770 $GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/$SAMPLE

	#create script to submit R script for MEDIPS QC
	SCRIPT_PATH=$GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/$SAMPLE/$SAMPLE.qualityMetrics.sh
	cp $BASEDIR/qualityMetrics.sh $SCRIPT_PATH
	chmod 770 $SCRIPT_PATH

	#create R script for MEDIPS QC
	R_SCRIPT_PATH=$GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/$SAMPLE/$SAMPLE.qualityMetrics.R
	cp $BASEDIR/qualityMetrics.R $R_SCRIPT_PATH
	chmod 770 $R_SCRIPT_PATH

	BAM_INPUT=$INPUT_DIR/$SAMPLE/$SAMPLE.nondup.rename.filt.bam

	sed -i -e "s/#Rversion/${R_VERSION}/" $SCRIPT_PATH
	sed -i -e "s/#inputBam/${BAM_INPUT//\//\\/}/" $SCRIPT_PATH
	sed -i -e "s/#Rscript/${R_SCRIPT_PATH//\//\\/}/" $SCRIPT_PATH

	LOG_OUTPUT_PATH=`echo $SCRIPT_PATH | perl -pe 's/\.sh/\.log/g'`
	echo -n "" > $LOG_OUTPUT_PATH
	chmod 660 $LOG_OUTPUT_PATH

	echo "`${NOW}`submitting job script $SCRIPT_PATH "
	JOB_ID=`qsub -q pqcgi -o $LOG_OUTPUT_PATH $SCRIPT_PATH`
	echo "`${NOW}`job ID: $JOB_ID"

	MEDIPS_DEPENDECIES="$MEDIPS_DEPENDECIES:$JOB_ID"

	MEDIPS_SAMPLE_DIR=$GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY/$SAMPLE

	sed -i -e "s/#sample/${SAMPLE}/" $R_SCRIPT_PATH
	sed -i -e "s/#medipsSampleDir/${MEDIPS_SAMPLE_DIR//\//\\/}/" $R_SCRIPT_PATH
	sed -i -e "s/#extendReads/${EXTEND}/" $R_SCRIPT_PATH
	sed -i -e "s/#pairedReads/${PAIRED}/" $R_SCRIPT_PATH
	sed -i -e "s/#windowSize/${WINDOW}/" $R_SCRIPT_PATH

done

#submit summary script
#if job is completed and log file is created in the run directory
#script displays plots and quality metrics on eliot

SUMMARY_SCRIPT_PATH=$GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/multisample/$PROJECT.summary_medips.pl
cp $BASEDIR/summary_medipsQualityMetrics.pl $SUMMARY_SCRIPT_PATH
chmod 770 $SUMMARY_SCRIPT_PATH

MEDIPS_RESULTS_DIR=$GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY
MEDIPS_RUNS_DIR=$GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY
SUMMARY_DEPLOYMENT=$DEPLOYMENT_BASE_DIR/project/$PROJECT/medips-QC/$TODAY
sed -i -e "s/#medipsResultsDir/${MEDIPS_RESULTS_DIR//\//\\/}/" $SUMMARY_SCRIPT_PATH
sed -i -e "s/#medipsRunsDir/${MEDIPS_RUNS_DIR//\//\\/}/" $SUMMARY_SCRIPT_PATH
sed -i -e "s/#deploymentServer/${DEPLOYMENT_SERVER//\//\\/}/" $SUMMARY_SCRIPT_PATH
sed -i -e "s/#summaryDeployment/${SUMMARY_DEPLOYMENT//\//\\/}/" $SUMMARY_SCRIPT_PATH

SUMMARY_LOG_OUTPUT_PATH=`echo $SUMMARY_SCRIPT_PATH | perl -pe 's/\.pl/\.log/g'`
echo -n "" > $SUMMARY_LOG_OUTPUT_PATH
chmod 660 $SUMMARY_LOG_OUTPUT_PATH

echo "`$NOW`submitting summary script: $SUMMARY_SCRIPT_PATH"
SUM_JOB_ID=`qsub -q $QUEUE -o $SUMMARY_LOG_OUTPUT_PATH -j oe -W depend=$MEDIPS_DEPENDECIES -M cgi@imperial.ac.uk $SUMMARY_SCRIPT_PATH` 
echo "`$NOW`job ID: $SUMMARY_SUM_JOB_ID"

echo "`$NOW`###########################################################################################"
#calculate corelation matrics for all samples

#create script to submit R script 
SCRIPT_PATH=$GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/multisample/$PROJECT.qualityMetrics.sh
cp $BASEDIR/qualityMetrics.multisample.sh $SCRIPT_PATH
chmod 770 $SCRIPT_PATH

#create R script 
R_SCRIPT_PATH=$GROUPVOL_TGU/runs/$PROJECT/medips-QC/$TODAY/multisample/$PROJECT.qualityMetrics.R
cp $BASEDIR/qualityMetrics.multisample.R $R_SCRIPT_PATH
chmod 770 $R_SCRIPT_PATH

MEDIPS_RESULTS_DIR=$GROUPVOL_TGU/results/$PROJECT/medips-QC/$TODAY/multisample

sed -i -e "s/#Rversion/${R_VERSION}/" $SCRIPT_PATH
sed -i -e "s/#inputBam/${INPUT_DIR//\//\\/}/" $SCRIPT_PATH
sed -i -e "s/#samples/${SAMPLES//\//\\/}/" $SCRIPT_PATH
sed -i -e "s/#Rscript/${R_SCRIPT_PATH//\//\\/}/" $SCRIPT_PATH

sed -i -e "s/#sampleInfo/${SAMPLE_INFO//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#medipsDir/${MEDIPS_RESULTS_DIR//\//\\/}/" $R_SCRIPT_PATH
sed -i -e "s/#extendReads/${EXTEND}/" $R_SCRIPT_PATH
sed -i -e "s/#pairedReads/${PAIRED}/" $R_SCRIPT_PATH
sed -i -e "s/#windowSize/${WINDOW}/" $R_SCRIPT_PATH

LOG_OUTPUT_PATH=`echo $SCRIPT_PATH | perl -pe 's/\.sh/\.log/g'`
echo -n "" > $LOG_OUTPUT_PATH
chmod 660 $LOG_OUTPUT_PATH

echo "`${NOW}`submitting job script $SCRIPT_PATH "
JOB_ID=`qsub -q pqcgi -o $LOG_OUTPUT_PATH $SCRIPT_PATH`
echo "`${NOW}`job ID: $JOB_ID"

MEDIPS_DEPENDECIES="$MEDIPS_DEPENDECIES:$JOB_ID"

echo "`$NOW`submitting summary script: $SUMMARY_SCRIPT_PATH"
SUM_JOB_ID=`qsub -q $QUEUE -o $LOG_OUTPUT_PATH -j oe -W depend=$MEDIPS_DEPENDECIES -M cgi@imperial.ac.uk $SUMMARY_SCRIPT_PATH` 
echo "`$NOW`job ID: $SUM_JOB_ID"

echo "`$NOW`progress and summary can be seen at $DEPLOYMENT_SERVER/report/project/$PROJECT/medips-QC/$TODAY"

